# Generated by Django 3.2.23 on 2024-01-03 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetails',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
