# Generated by Django 3.2.23 on 2024-01-04 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Signup', '0002_alter_myuser_user_id'),
        ('Home', '0004_alter_productdetails_product_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='BidderPriceList',
            fields=[
                ('bid_id', models.AutoField(primary_key=True, serialize=False)),
                ('bidPrice', models.IntegerField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.productdetails')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Signup.myuser')),
            ],
        ),
    ]
