# Generated by Django 3.2.23 on 2024-01-01 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Signup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='user_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
